monofony_demo_booking:
    resource: |
        alias: monofony_demo.booking
        section: backend
        except: ['show','index']
        redirect: update
        grid: monofony_demo_backend_booking
        vars:
            all:
                subheader: monofony_demo_backend.ui.managing_bookings
            index:
                icon: 'fax'
        templates: '@MonofonyDemoBackend/backend/crud'
    type: sylius.resource

monofony_demo_backend_booking_index:
    path: /bookings/
    methods: [GET]
    defaults:
        _controller: monofony_demo.controller.booking::indexAction
        _sylius:
            section: backend
            permission: true
            grid: monofony_demo_backend_booking
            template: "@MonofonyDemoBackend/backend/booking/index.html.twig"
            vars:
                subheader: monofony_demo_backend.ui.managing_bookings
                icon: cat

monofony_demo_backend_booking_show:
    methods: [GET]
    path: /bookings/{id}
    defaults:
        _controller: monofony_demo.controller.booking::showAction
        _sylius:
            section: backend
            template: '@MonofonyDemoBackend/backend/booking/show.html.twig'
            vars:
                templates:
                    breadcrumb: backend/booking/show/_breadcrumb.html.twig
                    toolbar: backend/booking/show/_toolbar.html.twig

monofony_demo_backend_update_state:
    methods: [PATCH]
    path: /bookings/{id}/status/{transition}
    defaults:
        _controller: monofony_demo.controller.booking::applyStateMachineTransitionAction
        _sylius:
            section: backend
            state_machine:
                graph: monofony_demo_backend_booking
                transition: $transition
            csrf_protection: false
            redirect: referer