monofony_demo_backend_partial_pet_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: monofony_demo.controller.pet::indexAction
        _sylius:
            repository:
                method: findLatest
                arguments: ['!!int $count']
            template: $template
